cosmos_db_endpoint : "https://news-app.documents.azure.com:443/"
cosmos_db_key : ""
database_name : "News"
container_name : "NewsArticles"
cache_container_name : "ChatHistory"
openai_endpoint : "https://richag-openai.openai.azure.com/"
openai_key : ""
openai_type : "azure"
openai_api_version : "2023-05-15"
openai_embeddings_deployment : "richag-embedding-deployment"
openai_embeddings_model : "text-embedding-3-large"
openai_embeddings_dimensions : "1536"
openai_completions_deployment : "richag-completions-model"
openai_completions_model : "gpt-4o"